d={chr(i+65):chr((i+13) %26+65) for i in range(26)}
dico={chr(i+65):0 for i in range(26)}
dico2={chr(i+65):0 for i in range(26)}
frequenceL = {"A":0.084,"B":0.0106,"C":0.0303,"D":0.0418,"E":0.1726,"F":0.0112,"G":0.0127,"H":0.0092,"I":0.0734,
 "J":0.0031,"K":0.0005,"L":0.0601,"M":0.0296,"N":0.0713,"O":0.0526,"P":0.0301,"Q":0.0099,"R":0.0655,"S":0.0808,
 "T":0.0707,"U":0.0574,"V":0.0132,"W":0.0004,"X":0.0045,"Y":0.0030,"Z":0.0012}


texte="""NOLED TESVVOD VOC PKELYEBQC N KSH OX ZBYFOXMO PEBOXD BOMYEFOBDC N EXO ZVESO NO CKXQ. XSMYVKC MVKENO PKLBS NO ZOSBOCM PSD NOC BOVOFOC NO MODDO ZVESO OX BOMEOSVVKXD AEOVAEOC QYEDDOC CEB VK WEBKSVVO NE MSWODSOBO NO VK MKDRONBKVO. SV NOMYEFBSD AEO M ODKSOXD VOC OHMBOWOXDC NOC MRBICKVSNOC NOC ZKZSVVYXC AES KFKSOXD ODO YLCOBFOC BOMOWWOXD. VO MOXDBO FSVVO X KIKXD ZKC ODO OXFKRS SV ODKSD BOCDO OZKBQXO. MODDO OHZVSMKDSYX CMSOXDSPSAEO XO MKVWK ZKC VK DOBBOEB ZYZEVKSBO . QBKMO OD VOQOBODO VO ZKZSVVYX OCD KE TKZYX EX OWLVOWO NO VK POWWO OD NOEH ZKZSVVYXC PSQEBOXD VO LYXROEB MYXTEQKV. VOQOBODO CELDSVO VOC ZKZSVVYXC CYXD NOC OCZBSDC FYIKQOEBC VOEB FEO KXXYXMO EXO FSCSDO YE VK WYBD N EX ZBYMRO. EX KEDBO KCZOMD NE CIWLYVSCWO NE ZKZSVVYX OCD PYXNO CEB COC WODKWYBZRYCOC VK MRBICKVSNO OCD V EP AES MYXDSOXD VK ZYDOXDSKVSDO NO V ODBO VO ZKZSVVYX AES OX CYBD OCD EX CIWLYVO NO BOCEBBOMDSYX. M OCD OXMYBO CS V YX ZBOPOBO VK CYBDSO NE DYWLOKE. CIWLYVO NE POE CYVKSBO OD NSEBXO OD ZYEB MODDO BKSCYX NO V KWO NOC QEOBBSOBC SV BOZBOCOXDO VO CYVOSV NKXC VO DOWZVO NOC QEOBBSOBC KJDOAEOC OD VO NSOE NO POE ZYBDO MYWWO OWLVOWO EX ZOMDYBKV XYWWO ZKZSVVYX N YLCSNSOXXO. V YLCSNSOXXO MYWWO VO CSVOH OCD EXO ZSOBBO NO POE. DYEDOC MOC SXDOBZBODKDSYXC NOMYEVOXD ZBYLKLVOWOXD NO V KCCYMSKDSYX KXKVYQSAEO NE ZKZSVVYX OD NO VK PVKWWO NE PKSD NO COC MYEVOEBC OD NE LKDDOWOXD NO COC KSVOC . NKXC VK WIDRYVYQSO QBOMAEO ZCIMRO V KWO WKBSOO K EBYC V KWYEB KMAESOBD NOC KSVOC NO ZKZSVVYX VK ZOSXDEBO PBKXCKSCO XYEBBSO NO WIDRYVYQSO PKSD PSQEBOB NOC ZKZSVVYXC K MYDO NO ZCIMRO NKXC VOC DKLVOKEH AES VK BOZBOCOXDOXD. OX QBOM KXMSOX ZCEURO CSQXSPSO K VK PYSC KWO OD ZKZSVVYX . KBDC"""    


#calcule des nb lettres
for j in texte:
    for i in dico:
        if i==j:
            dico[i]+=1

#calcule%
for k in dico2:
    dico2[k]=(dico[k]/len(texte))


#maxlettre
inverse = [(value, key) for key, value in dico.items()]
Max=max(inverse)[1]
print (max(inverse)[1])

#clé_décalage
clé=ord(Max)-ord("E")
if clé<0:
    clé=clé+26
        
#décodage
def decodage(texte,clé):
    decodage={chr(i+65):chr((i-clé) %26+65) for i in range(26)}
    res=""
    x=0
    for i in texte:
        x=0
        for j in d:
            if j==i:
                res=res+decodage[j]
                x=1
        if x==0:
            res=res+i
    return res
        
print(clé)                                 
print(decodage(texte,clé))
